services:
  postgres:
    image: postgres:latest
    container_name: vuka_db
    environment:
      POSTGRES_USER: vuka
      POSTGRES_PASSWORD: pass@vuka
      POSTGRES_DB: vuka
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data:
